### ISSUE TITLE
Ultimate Image Browser will not run on Windows 7 64-bit

### ISSUE THREAD

**Issue by denistotoliciu** [fysnet/FYSOS#3]
Tried to run both Ultimate 32-bit and 64-bit executables on Windows 7 64-bit, but the error messages that are in the attached files were displayed:
[Error Messages.txt](https://github.com/fysnet/FYSOS/files/9885017/Error.Messages.txt)

**Comment by fysnet** [comment]
I'm sorry, I do not have a Windows 7 machine to test with.  The first two errors seem reasonable since you didn't have administrative rights.  The last two errors are a complete loss to me.  Why wouldn't it find the file?
Anyway, sorry I can't be more help.  I don't know much about Windows 7 at all.  I went from working with WinXP for years and years straight to Win10, skipping Windows 7, 8, Vista, etc.

**Comment by fysnet** [comment]
Just a thought, could Win7 be case sensitive?  You are typing ultimate when you should be typing Ultimate.

**Comment by denistotoliciu** [comment]
I found out that the problem is on my part. The files **ultimate.exe* and **ultimate64.exe* were actually HTML files, but having the .EXE extensions.
I have just downloaded the actual .EXE files and have run them and they start up smoothly and work out of the box.
My appologies for reporting it as an issue.

**Comment by fysnet** [comment]
no worries at all.  I am glad you got it to work.
